apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ypxdn04s0-nodejs
  janus-idp.io/tekton: ypxdn04s0-nodejs
  backstage.io/kubernetes-id: ypxdn04s0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ypxdn04s0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
